pipeline:
  run:
    image: python:3.7-alpine3.8
    commands:
      - python3 test.py
  deploy:
    image: appleboy/drone-ssh
    host:
    username: root
    secrets: [ ssh_key ]
    port: 22
    script:
      - cd /var/www/xx
      - git pull
      - cat

branches: master
